### ISSUE TITLE
Smokeping graphs not showing

### ISSUE THREAD

**Issue by pdxmaverick** [inex/IXP-Manager#122]
I have smokeping running and configured with /usr/local/ixp/bin/ixptool.php -a smokeping-cli.gen-conf

application.ini:
smokeping.conf.dstfile = '/etc/smokeping/config'
smokeping.conf.cgiurl = "https://portal.nwax.net/smokeping/smokeping.cgi"
smokeping.conf.imgcache = "/usr/share/smokeping/www/img"
smokeping.conf.imgurl = "/smokeping/img"
smokeping.conf.datadir = "/usr/share/smokeping/var"
smokeping.conf.piddir = "/etc/smokeping"
smokeping.conf.smokemail = "/etc/smokeping/smokemail"
smokeping.conf.pathnames = "/etc/smokeping/config.d/pathnames"
smokeping.oconf.tmail = "/etc/smokeping/tmail"
smokeping.oconf.syslogfacility = "local0"

In smokeping I see my members. 

Ex: https://portal.nwax.net/smokeping/smokeping.cgi?target=infra_1.vlan_1.vlanint_14_ipv4

In IXP I do get the smokeping button but I do not get graphs when I go to that page
Ex: https://portal.nwax.net/ixp/smokeping/member-drilldown/ixp/1/vi/14

Thanks,
Brian

**Comment by MHammett** [comment]
I would also like to note that if you configured it incorrectly (with the server's public instead of loopback IP) to start with and then change your public IP, you'll break your graphs. They'll take forever to timeout, then displaying, "No image found".

Do it right the first time (by using 127.0.0.1) so you don't have to do it again. Added for future Googlers.
