### ISSUE TITLE
Alphabetical sorting of IP addresses rather than numerical

### ISSUE THREAD

**Issue by rowanthorpe** [inex/IXP-Manager#21]
When clicking the arrows on the web-interface to sort ipv[46]addresses, they are sorted "alphabetically", e.g.:

    192.168.1.1
    192.168.1.10
    192.168.1.2

The sort needs to be changed to "numerical" for these to be meaningful. This also impacts on ipv6 addresses, keeping in mind that it needs to "numerically" sort hex-numbers .

**Comment by listerr** [comment]
I know this might be considered a "frontend niceness" but it makes assigning IP addressees a complete pain and unhelpful, and the process makes no sense. It is not as straightforward as "go to the bottom of the list, find the next free one and assign it." 

It is "pick through the list of addresses until you get to a high numbered one that looks like it may or may not be in the right sequence" (and a host of other IP address management issues...)

Also **VERY ANNOYING** is that this list **always defaults to IPv6** when I never, ever care about IPv6 in this page, or assign IPv6 addresses in this way, since we already know what those are going to be, they're never picked from a list. I know you want to evangelise IPv6 and all that, but _IXPs are already sold on IPv6_. It just adds a needless annoying extra click in an already awkward workflow in the admin interface.

With the migration to Laravel, is there some possibility that this can be fixed?
