### ISSUE TITLE
Registered Name field, please increase length

### ISSUE THREAD

**Issue by apolyr** [inex/IXP-Manager#213]
The registered name field is 64bytes, however this is not long enough to hold unicode strings:

eg: 'Εθνικό Δίκτυο Έρευνας & Τεχνολογίας. Α.Ε' is more than 64 characters long

please increase to a larger value (eg 256)

**Comment by rowanthorpe** [comment]
Just to clarify: that entry is 40 characters long, which in utf-8 is 75 bytes long. Aside from any potential issue of limit-enforcement/validation within the interface itself (if it exists for that field), in the Doctrine schema file:

> doctrine/schema/Entities.CompanyRegisteredDetail.dcm.xml

I don't see any size-limit for that field, so I presume this is a case of the database picking an arbitrary
limit, and for now if we manually increase it in the database there should be no conflict with Doctrine, yes...?

**Comment by barryo** [comment]
I'll look at this properly later in the week @rowanthorpe but it might just be an arbitrary length here:

https://github.com/inex/IXP-Manager/blob/master/library/IXP/Form/Customer/BillingRegistration.php#L175

However, I may need to dig deeper as Zend seems to use `iconv_strlen` which correctly returns 40:

```php
echo iconv_strlen( "Εθνικό Δίκτυο Έρευνας & Τεχνολογίας. Α.Ε" ) . "\n"
```

**Comment by rowanthorpe** [comment]
Update (I didn't have access to the database before). In the database we have (as I'd expected):

> show create table company_registration_detail;
> ..[snip]..
> `registeredName` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,

So Doctrine & the database don't contribute to this limit at all. It is only on the interface-level which @barryo mentions above.

I found that in the zend stringValidate code it optionally pulls the encoding as a third parameter, and otherwise picks a default encoding. According to [this stackexchange post](https://stackoverflow.com/questions/6803907/zend-validate-stringlength-encoding) it seems it doesn't necessarily default to UTF-8, but instead sniffs the encoding iconv_get_encoding(). I still find this surprising because our servers have UTF-8 as default locale system-wide. I added 'UTF-8' as third parameter to the call on our staging server, and it allowed me to update the field with "Εθνικό Δίκτυο Έρευνας & Τεχνολογίας. Α.Ε" OK, so the remaining question is whether *all* the calls to stringValidate need to explicitly include that third parameter, or whether there is some internal config that needs explicit setting to 'UTF-8', or (gulp) whether there is something about our setup which is convincing zend not to use UTF-8. In the meantime I will PR the change I made for reference. If it turns out that is the way to go let me know and I will make that change to *all* the callers to stringValidate().
