### ISSUE TITLE
Search facility on "Peer to Peer Statistics" page

### ISSUE THREAD

**Issue by spaprzycki** [inex/IXP-Manager#248]
It would be extremely useful if basic search was available for peer to peer graphs. It would significantly improve user experience when one need to browse graph for specific peer (ideally searchable by name or ASN). It would probably also reduce load on the machine storing RRD files - no need to read and graph all RRD files when only one is required.

**Comment by barryo** [comment]
Cheers @spaprzycki. On another IXP's implementation, the landing page is a list of members rather than graphs (as they have many more). Might swap INEX's over to that pending more intelligent information display.

Closing as this is implemented and more advanced features are on the implementation plan.

**Comment by spaprzycki** [comment]
@barryo just had a chance to test it now.

I think you introduced little bug for dual (or more) topology LANs - there is no way now to display all graphs for non-default peering LAN (such as "Peering VLAN #2" at INEX). When selecting secondary LAN, submit takes to list of graphs (that's ok), but 'Show Graphs' from there leads to all graphs for main/primary LAN - hope this explanation make sense :)

**Comment by barryo** [comment]
Indeed I did. Will fix tomorrow. Thanks @spaprzycki
