### ISSUE TITLE
physical interfaces in a port group should be restricted to a single switch

### ISSUE THREAD

**Issue by nickhilliard** [inex/IXP-Manager#270]
If there are physical interfaces added into an existing virtualinterface from different switches, several things will break, including sflow stats.  The physical-interface/add/vintid/xx URI needs to check that any new physicalinterface belong to the same switch as any existing physicalinterface before adding it to the group.

**Comment by listerr** [comment]
I remember mentioning this to Barry some time ago, along with some other
sanity checking such as making sure the ports in a LAG were all the same
speed etc. He was reluctant to introduce this level of complexity into
the interface.

When a member moves or upgrades ports, I add the new port into the 'LAG'
otherwise we lose the records about the old interface and/or lose the
graph history for the port.

The move/upgrade process is a bit clunky at the moment. If I provision
the new port under a new Virtual Interface, then moving the IP addresses
is a PITA.

(having to renumber/delete IP addresses from one vlan interface, so move
5.57.80.10 to 5.57.80.222 so it doesn't clash, save it, configure this
IP on the new interface, save it, tap it all in again for IPv6 as the
auto-assignment thing gives it a new address and not the existing
address.... etc.)

For port moves, we like to keep visible in the database the old and new
ports for a period of time. When the member is happy, after perhaps 2
weeks, the old ports will be disabled and we can delete them from their
account. (We have a separate process to mark a port as "To be unplugged"
on the switch, before it is usable again, however, before we can
automate these things, we'd need to keep a record somewhere of ports
that need cleaning up/cables to be unplugged/cable IDs etc, otherwise we
lose track of this data at present as it's just deleted.)

(I record the cable ID in the "notes" box for the physical interface. If
this is deleted, then we lose this ID. So I also keep this record in the
account notes, or we lose knowledge of things like spare cables etc.)

'old ports' or 'old members' in general aren't catered for at all in the
current interface, for example addresses that are sponged.

(When a member disconnects, we ARP sponge the address, however, the IXP
Manager interface doesn't have any way to record that. I manually moved
them to a "Sponged" vlan to prevent them from being made available again
to new ports.)

When a port is moved or a change is made, there's no history kept
anywhere which can sometimes make things like billing problematic.
A note should be recorded in the system when ports are provisioned /
unprovisioned.

Currently we do this manually by adding notes to the account, to try to
record as much detail as possible about what's happened, so that we can
bill correctly for, say, a member that upgraded mid-year from 2x1G to
1x10G, in 6 months time, we need to know on what date the upgrade took
place, and to keep a note of the spare cable freed up.


Rob



On Fri, 12 August, 2016 at 5:50:46 PM, Nick Hilliard wrote:

> If there are physical interfaces added into an existing
> virtualinterface from different switches, several things will break,
> including sflow stats.  The physical-interface/add/vintid/xx URI needs
> to check that any new physicalinterface belong to the same switch as
> any existing physicalinterface before adding it to the group.


Regards,


Rob


-- 
Rob Lister
rob@lonap.net
+44 20 3137 8330

**Comment by barryo** [comment]
> needs to check that any new physicalinterface belong to the same switch as any existing physicalinterface 

While we don't support (or have kit that does) multi-chassis LAGs, others may. If we enforce the OP's request, what happens to this use case?

**Comment by nickhilliard** [comment]
good point.  This leaves options: 1. live with it as-is or 2. create a
configuration flag to turn on / off this as a feature.  #1 is
undoubtedly easier.

**Comment by barryo** [comment]
I'm going to go with (1) for now on the assumption that IXP operators are reasonably intelligent 😄
