### ISSUE TITLE
SNMPv3 Support

### ISSUE THREAD

**Issue by jamestutton** [inex/IXP-Manager#309]
Depending where it sits on any roadmaps I like to request support for SNMPv3 as part of the discovery and other processes.  

As I had an immediate need I also would like to propose a quick and dirty fix to support it which i have added to my install for now.

In effect the trick is to use the current Community Field and add some special case handling.

So as the Community we use a bit of JSON with form:

`{"SNMPv3":{"authprotocol":"MD5","authpassphrase":"##AUTHPASS##","community":"##CONTEXT##","seclevel":"AuthPriv","privprotocol":"AES128","privpassphrase":"##PRIVPASS##"}}`

Then in the SNMP Calls we replace the code with:
`try
                {
                    $swPolled = false;
                    $host = $sw->getHostname();
                    $community = $sw->getSnmppasswd();
                    $version = '2c';
                    $seclevel = 'noAuthNoPriv';
                    $authprotocol = 'MD5';
                    $authpassphrase = 'None';
                    $privprotocol = 'DES';
                    $privpassphrase = 'None';

                    //Is it SNMPv3 Config
                    if (preg_match('/{"SNMPv3":(?P<V3Conf>{.*})}/',$community,$m)) {
                      $V3Conf = $m['V3Conf'];
                      $SNMPv3 = json_decode($V3Conf);
                        if (json_last_error() != 0) {
                                $this->addMessage( 'The JSON Encoded passed is invalid.
                                Example Conf {"SNMPv3":{"authprotocol":"MD5","authpassphrase":"...","community":"...","seclevel":"AuthPriv","privprotocol":"AES128","privpassphrase":"..."}}',
                                OSS_Message::ERROR );
                                break;
                        }
                      $community = $SNMPv3->community;
                      $seclevel = $SNMPv3->seclevel;
                      $authprotocol = $SNMPv3->authprotocol;
                      $authpassphrase = $SNMPv3->authpassphrase;
                      $privprotocol = $SNMPv3->privprotocol;
                      $privpassphrase = $SNMPv3->privpassphrase;
                      $version = 3;
                    }
                      $host = new \OSS_SNMP\SNMP( $host , $community , $version , $seclevel  , $authprotocol  , $authpassphrase , $privprotocol , $privpassphrase );

                    //$host = new \OSS_SNMP\SNMP( $sw->getHostname(), $sw->getSnmppasswd() );`

**Comment by barryo** [comment]
Hi @jamestutton - I definitely don't want to put you off contributing to IXP Manager (and I have noted your updates on two other tickets). But just on:

> As I had an immediate need I also would like to propose a quick and dirty fix to support it which i have added to my install for now.

It's not the worst *quick and dirty fix* I've seen 😉   And IXP Manager has quite a few of these to be fair. But a lesson we've learnt is that we come to rue the day we accept these because, without exception, every single quick+dirty fix comes back to bite us later. In different ways.

For example the code to discover/add switches should not be in an entity class (my fault!), should not require only SNMP as an option (my fault!) and so on. This all needs to be abstracted out in two ways:

1. decouple discovery from the entity
2. decouple discovery from SNMP

Adding more hacks to the existing codebase just makes it harder to decouple down the road.

Separately, we've had SNMPv3 come on on the mailing list recently:

https://www.inex.ie/pipermail/ixpmanager/2017-March/000979.html

So, based on all of the above, we won't merge this in I'm afraid but it is on our list to do "the right way".
