### ISSUE TITLE
[RFC] Authentication and User Management

### ISSUE THREAD

**Issue by barryo** [inex/IXP-Manager#354]
As we near the final elements of Zend Framework and migrate them to Laravel, one of the bigger remaining issues is authentication and access control.

Generally, we would like to make the following major changes to the existing system:

1. remove usernames and replace with an email address. Usernames seem to be a thing of the past with most online services keying off of a confirmed email address. This also has the upsides of avoiding username collisions and *I forgot my username* issues. An artisan migration command would be provided for this. As well as a template email to be sent to all users with the script sending this email as part of the process.

2. allow an email address to be linked to more than one customer / network. In this industry, many people act for multiple networks and having multiple logins is awkward. You would chose your network from a dropdown in the top right in the same way as you do when you have multiple LIR portals on RIPE. This matches RIPE's newer system (just using RIPE as an example). If you go to add a new user to your IXP Manager customer account, you enter the email. If they exist on the system, they get an email letting them know, otherwise they get a welcome email as a new user with instructions for setting the password, etc.

3. Unshackle contacts from users. Linking users and contacts (such that every user is a contact first) was a requested feature which was not thought through properly and doesn't work too well in practice. A contact is not a user and a user is not necessarily a contact. We have no problem loosely coupling these for informational purposes (by the way, this user is the same as this contact) but the tight coupling which has essentially hidden users behind contacts has created very hacky and unmaintainable code in the authentication section of the IXP manager (where it's the last thing you need); has added some frontend confusion; the schema was not designed for this; and it just feels clunky. Again, an artisan command would be provided to do the heavy lifting here.

4. change the authorisation system from the current roles of CUSTADMINs and and CUSTUSERs (if you don't know what these are, [see here](http://docs.ixpmanager.org/usage/users/#types-of-users)). These date from the **old** RIPE LIR portal where identical roles existing. Instead, we would like CUSTADMIN to mean read/write/admin access and CUSTUSER to mean read-only access. All existing CUSTADMINs would be deleted (these users can only manage accounts and have no other purpose, they are usually role email addresses such as peering@/noc@). All existing CUSTUSERs would be elevated to CUSTADMINs. Each organisation could then - based on the *welcome to your new portal / here's some changes to your account* email, login and demote / manage users as appropriate.

These are big changes and would probably be released as v5 including the completion of the removal of all Zend Framework. 

### 2-Factor Authentication

We plan to introduce 2fa using the standard Time-based One-time Password Algorithm (TOTP). While this may be useful for end users, the primary target for this is SUPERADMINs (IXP staff). There will be an option to continuously alert a SUPERADMIN that they have not enabled this *on every page until they do*. We may also make it an option to make this mandatory so a SUPERADMIN can do nothing else once logged in initially until 2fa is enabled.

Other SUPERADMINs will be able to disable it for any other user so it can be reset.

### PeeringDB OAuth Linkup

This relates to #322 and peeringdb/peeringdb#131. IXP Manager will support being a client of PeeringDB's OAuth system. This support will be a configurable option. My initial general thoughts on this are in #322 and comments can be directed there.

**Comment by listerr** [comment]
All interesting.. As possibly related to this - it would be a good progression from this to allow our other apps to authenticate from IXP Manager in to other things rather than having a username/password recorded in multiple places.

**1. E-mail addresses as usernames**

- Probably friendlier for the user, not having to remember a bunch of different logins etc. Need to check if this username format is compatible with everything that it might be used with it (TACACS etc and other authentication backends)

- Possible confusion if user can access multiple customers. If they register as joe@customera.com and then leave that organisation, but have access to other customers, we'd need a way to reconcile that situation so they can change their e-mail address and/or we're not sending password recovery e-mails to their old e-mail address, for example. Possibly the only way to resolve this is to raise a support ticket. (The admin at "customera.com" can remove the user from accessing their customer data, but then may want to "delete" that account because it is using their domain name.) Not sure.. ask for a secondary backup e-mail address?

- If system's user/password list is compromised, provides a handy list of e-mail addresses and passwords etc to try at other sites. The reverse is also true if another site is compromised, people can try the same credentials at IXP Manager, though I don't see it as being very interesting for people to attack.

- Possibly other privacy things to consider where e-mail addresses are appearing in parts of the system, especially if other users can see things, though I can't think of anything where this is important in IXP Manager except for example logs and where .htpasswd type files are being generated from IXP Manager in to other systems, e-mail addresses might show up in other log files.


**2. User login to multiple customers**

When we were starting to design our own system before IXP Manager came along, we thought about a single username being able to log in to multiple members, and there are for example a few use cases i.e. consultants who look after multiple ISPs, or where companies have merged, or the same organisation looks after multiple ASNs, and the same users want to see both ASNs.

Our conclusion was that:

- It was probably a "nice to have" in that there are only a tiny number of usernames that would want this functionality.

- If we did have this functionality and had automation or other critical things, the interface would have to be **super clear** at **all times** which customer the user was acting on, and this would require strict tracking of which customer the user was looking at and it would have to be robust e.g. no "bouncing back" to a "default" or "first customer in the list" just because the interface can't handle it, and if we don't know, bounce back to a screen asking them to select. (Ask at every login and then maybe even require the user to log out to select a different customer?) This is to avoid possibly embarrassing errors ether because the user didn't notice which customer they were editing, or the interface quietly flipped them back to another customer after a particular action. Errors could include: adding users to the wrong customer, cancelling the wrong port, changing the billing info on the wrong account, deleting someone from the wrong customer etc, etc.

- User history log would need to include some detail about which customer the user was accessing and any transactions performed in that customer.  Anyone from that customer with enough access should be able to see history for users on that customer only. (rather than all transactions for other customers for a particular username.)

- In the end, we decided that it probably was not worth the extra risk of coding it for the small number of users who would actually need it -- these people can probably cope with having multiple logins, and it makes it clear to each member, who has access. If IXP Manager can implement it so it's very clear at all times in the interface which customer it is, then this would be a good feature. Examples are in the current **admin** interface, it is not clear in places, for example in the **edit physical interface** screen. /physical-interface/edit/id/xx/vintid/xx - nowhere on this page does it display which **customer** I'm working on. **During bleary-eyed maintenance slot**, I need to change a bunch of these having migrated a load of ports, and be sure which one I'm working on. Look away to another window to get some more information, or get distracted and then come back to this screen? Ook... Who am I editing again?  :-)  Once the user is logged in, **Every page** in the interface needs to display something like: "Logged in as user@domain.com, AS XXXXX, - Customer Name / Editing: ...."

It would also need to be clear for the users with sufficient rights, who was able to access their customer data and to grant/deny access as appropriate.

**3. Unshackle contacts from users**

I think we prefer to have every username associated with a contact, then when someone is requesting access, we have their contact details. I can't think of any cases where we'd have a user without an associated contact?

On the other hand, we often add contact entries for people that do not have a username.

I agree that parts of this are awkward, for example the mailing list subscriptions being held as properties in the **user** table, and this e-mail address is stored separately from the contact's e-mail address. We've since turned the mailing list sync feature off, as it doesn't quite work for us and is clunky to administer from within IXP Manager.  (I really just want to pass a list of contact e-mail addresses to a Mailman list based on contact groups which the user can select.) I set all this up, only to find that the user cannot select which contact groups they are in. Currently, only an admin or custadmin can do that.  :(

Importantly, checking needs to occur for example when a customer has left the exchange, or access suspended, that the usernames are also disabled.

**4. change the authorisation system from the current roles of CUSTADMINs and and CUSTUSERs**

Yes. This would be much better.

Though my selection process would not be to make them all CUSTADMINs.

For most members who joined since IXP Manager, the CUSTADMIN is NOT a role, but the e-mail address will be of the person who bootstrapped the member joining /username creation process. For most of those its simply a case of:

If there is only one other user that is NOT a CUSTADMIN, make this user the CUSTADMIN.
(Most small members fall in to this category)

Where the CUSTADMIN e-mail is NOT a role/NOC/peering address, and it matches one of the other contacts, make this person CUSTADMIN. Create a new custadmin user if needed. (This works for us because of the way we have signed up new members. I suspect this would catch most of the active users who signed up since IXP Manager.)

If there's no other users than CUSTADMIN, we'll need to sort that out somehow (perhaps a contact with Admin and Technical roles could be a candidate to e-mail?)

Some members have a lot of usernames and we might not be able to pick the out using the above rules. So, we will need to decide which ones are likely candidates for the CUSTADMIN. Probably based on their Job Title, what role boxes they've got ticked, most recent login etc.

Fix up mailing list subscriptions prior to deleting CUSTADMIN.

**2-Factor Authentication**

How would this work? A separate system or using an existing method e.g. Google Authenticator?

**Comment by listerr** [comment]
- But yes.. Redesigning the user / contact / cust relations so that the user table is more self-sufficient to enable better / alternative authentication mechanisms and possibly access to multiple custs probably needs to happen. 

I'd be mostly concerned about data loss for example people logging in that we did not have any details for or insufficient logging of what users have been doing.
