### ISSUE TITLE
Can't change default SNM port

### ISSUE THREAD

**Issue by atamanbg** [inex/IXP-Manager#367]
Hello, 

I have few switches with different than default SNMP port (161).

How can I add my custom SNMP port?

**Comment by nickhilliard** [comment]
The short answer is that you can't - IXP Manager uses udp/161, snmpv2, and only depends on a restricted set of MIBs which are almost universally available on all platforms.

The longer answer is that the SNMP protocol is very configurable, e.g. you can use different ports and protocols, different communities for accessing different parts of different MIBs on the same network device, different versions of SNMP, usernames, passwords and lots more. There is a development and maintenance cost associated with supporting these things, but the value of supporting additional knobs is marginal, given that almost everyone and everything supports snmpv2/port161/udp out of the box.  If it isn't supported on a particular ixp, it's because someone has changed the defaults due to a requirement on their side.
