### ISSUE TITLE
The installer should check that the universe repository is enabled

### ISSUE THREAD

**Issue by rfc1036** [inex/IXP-Manager#373]
Or else it will fail because some packages will not be available.

Servers created with debootstrap will not have universe enable by default, so this is a common enough case that it should be checked.

**Comment by barryo** [comment]
Hi Marco,

the installers directory comes with information and instructions by way of [the README.md here](https://github.com/inex/IXP-Manager/tree/master/tools/installers). One of the things it says is:

> These install scripts are opinionated! They are intended to run exactly as specified and only on the operating system they are targeted at.

I'm pointing this out to try and nicely say thanks for pointing this out but, to be perfectly honest and realistic, we just do not have the bandwidth to cover different operating systems let alone the many and myriad of ways one can approach even a single version of a single OS 😢 

If you're willing to sign the [contributors agreement](https://github.com/inex/IXP-Manager/blob/master/CONTRIBUTING.md) and submit a PR for this, we'll happily look at it. Otherwise, I'm afraid to say that the script(s) need to be run as indicated.

Note that these scripts - as well a providing a useful install on the targeting platforms - as also and primarily intended to document the process from bare bones.
