### ISSUE TITLE
Please report quarantine status in the provisioner API

### ISSUE THREAD

**Issue by rfc1036** [inex/IXP-Manager#405]
##### ISSUE TYPE

 - Feature Idea

##### STEPS TO REPRODUCE

I use the experimental `/v4/provisioner/layer2interfaces/switch-name/` API, but when I change the status of a port from "Connected" to "Quarantine" this is not reflected in the data.

##### EXPECTED RESULTS

It would be helpful if this value were represented by the API to be able to use it in provisioning tools.

**Comment by nickhilliard** [comment]
implemented in e2d9775d9105236e5a702e806f0c4e24f593c49f.

This is straightforward for physical ports.  For LAG master ports, it's been implemented as:

- if any of the underlying physical ports is set to `connected`, then the LAG master port is set to `connected`
- if *all* of the underlying physical ports are set to `quarantine`, then the LAG master port is set to `quarantine`
- otherwise the LAG master port is set to `notconnected`
