### ISSUE TITLE
Billing Details re-organisation

### ISSUE THREAD

**Issue by apolyr** [inex/IXP-Manager#476]
I find the "Billing Details" section a bit confusing and ambiguous, and I would like to propose a small renaming/reorganisation of the fields.

I propose the section to be reorganised as follows (fields remain the same, unless otherwise stated):

 - VAT Rate
 - VAT Number
 - Billing Frequency
 - Purchase Order Required

 - Invoice method 
      (if invoice=email)
      - Invoice E-Mail
      (if invoice=post)
      - Recipient (rename from "Contact. It is confusing, as billing contacts exist elsewhere.")
      - Address
      - City
      - Postcode
      - Country
      - Telephone
      - E-Mail 

Notes: 
1. I find the e-mail field very confusing. I already have elsewhere the emails of all billing contacts. And I have an Invoice email. What was the intended use of this field? maybe it should be dropped...
2. Maybe you should add an invoice method "post+email", where all options will be present. A member might want to receive both electronic and hard copy invoices.

@listerr , @barryo mentioned that I should check with you with regard to this request. Does it sound reasonable?

**Comment by listerr** [comment]
I agree that the order of the fields could be improved.

In our case, there were two separate "billing" email address fields in our old database. One was used for the individual billing contact, and then another field was used for the email address to send the invoices, as this is often different to the contact. If the invoice email address was filled in, the invoice went to this address, otherwise, it goes to the contact.

We stopped sending out invoices by post a few years ago, so effectively we ignore the method field.

The email address should be underneath the "contact" name. Though in reality a lot of the time this just reads "Accounts Payable" or "Finance Department"

I agree that given that there is a contact flag for contacts for "billing" that the extra contact detail in here seems a bit redundant, but it makes for an easier update to the finance system rather than having to deal with possibly multiple contacts. (We're now on our third accounting system and they are all slightly different in how they deal with contacts, ranging from totally inflexible, to multiple contacts in different places which may or may not be used for anything.)

The idea is to eventually get to one system as the single source of truth.

Not all of our custs have a contact flagged as "billing", and we need to always make sure there's at least one usable billing contact, so the "billing" flag in the contacts is really for information only at the moment as "people we might also try to contact if the invoice bounces/they do not pay".

A couple of changes I would make: 

- The "PO Required" field should just become a field for "PO Number" because we have to record this elsewhere. If it's filled in, then we print it on the invoice. Knowing a "PO is required" without the PO Number itself, and not allowing the customer to see or update it, is useless.

- I've never really been sure exactly how the "VAT rate" field is used. Seems to me that it should be a drop-down list of options instead of free text.

- Possibly get rid of the contact email address in Billing, and just have contacts with the "Billing" role able to select if they wish to receive a copy of the invoice by email. (Since this is in reality what is happening in our accounts system which has a "primary" contact for billing, and allows for any number of "secondary" contacts which have a tick box for "send a copy of invoices")

**Comment by listerr** [comment]
Oh, and also needed is a billing system account ID field, so that the cust can be tied to the record in the accounting system.

Right now, we have to use an external (manually edited) table to link custs in IXP Manager <-> Xero accounting system ID, and the records can be "many to one" in that some accounts in Xero pay for multiple custs in IXP Manager.

**Comment by barryo** [comment]
## Housekeeping Sept 2021

@barryo closing long running issues (open multiple years). 

Where appropriate, will:

1. relocate to the [IDEAS file](https://github.com/inex/IXP-Manager/blob/master/IDEAS).
2. Add additional information below.
3. No relocation / additional information for uber-stale issues.

*Additional info: moved to ideas. Third party ref covered by another ticket.*
