### ISSUE TITLE
Idea: IX-API integration

### ISSUE THREAD

**Issue by netravnen** [inex/IXP-Manager#555]
**Is your feature request related to a problem? Please describe.**

Operational automation support. 

- NOTE: Going live with EPF in Tallinn, Latvia, next week.
- Homepage: https://ix-api.net/ (Not live at time of issue creation)

**Comment by barryo** [comment]
It's not at all clear what this is or what it relates to.

Maybe reopen after it goes live?

**Comment by netravnen** [comment]
> Maybe reopen after it goes live?

It is live now. Reopen?

**Comment by netravnen** [comment]
> Maybe reopen after it goes live?

Website is live now with information.

@barryo Re-open?

**Comment by schadom** [comment]
@barryo - now we have 2022, any updates? Thanks in advance

**Comment by barryo** [comment]
Still on my list of things to look at properly.

@schadom - what might help is real world use cases and benefits you might see your IX or other IXs benefiting from if IX-API was implemented? One of the things I'm struggling with is the real benefits of doing this above other things on our development list. Mostly people are saying / asking for this to be implemented but not actually *selling me* on the idea if you know what I mean?

**Comment by schadom** [comment]
Thanks @barryo . I do see an use case in centralized management and automation among all IXPs a network is connected to. For example centralized management of all RS peerings at all IXPs a network is connected to within a central dashboard. Especially for larger networks peering at many different locations this might be very handy. Since IXP Manager already has a built-in API which is deployed at atleast 182 IXPs vs. only three IXPs that currently support IX-API, maybe it would be the better approach if [@Peering-Manager ](https://github.com/peering-manager/peering-manager) might add support for the IXP-Manager API in the future than the other way around ;-) BR
