### ISSUE TITLE
FR: Support for Cisco's ingress+egress sFlow

### ISSUE THREAD

**Issue by rasssta** [inex/IXP-Manager#649]
**Is your feature request related to a problem? Please describe.**
Cisco Nexus boxes (and some others as well perhaps?) currently only support combined ingress+egress sFlow export and not *only* ingress. As the sFlow P2P statistics relies on *ingress only*...well...yeah it's a problem.

**Describe alternatives you've considered**
Since sflowtool v5.0.0, it allows for custom lines using the "-L" parameter. If sourceID and inputPort are the same, it's ingress related data. If it's not, then it's egress and can be discarded.

I did a quick'n'dirty test and got the following output from "-L sourceId,inputPort":
```
sourceId 0:1000014
inputPort 1000014
```

As you can see it's *almost* the same, but I'm sure you get my point here without further explanation :-)

So if you customize the sflowtools output line (and remove unneccessary info while at it) and then customize sflow-to-rrd-handler to perform a check for sourceId vs inputPort, this will enable support for NX-OS devices while being compatible with *ingress only* switches at the same time.

**Comment by nickhilliard** [comment]
sflowtool's implementation of -L currently doesn't support some of the sample information that we need - see sflow/sflowtool/pull/34.

Otherwise this is a good idea and we'll implement it if InMon fixes the code.

Note to self: the existing output is very roughly equivalent to:

`-l -L
sampleType,agent,inputPort,outputPort,srcMAC,dstMAC,ethernet_type,in_vlan,out_vlan,srcIP,dstIP,IPProtocol,IPTOS,IPTTL,TCPSrcPort,TCPDstPort,TCPFlags,IPSize,sampledPacketSize,meanSkipCount
`

**Comment by barryo** [comment]
## Housekeeping Sept 2021

@barryo closing long running issues (open multiple years). 

Where appropriate, will:

1. relocate to the [IDEAS file](https://github.com/inex/IXP-Manager/blob/master/IDEAS).
2. Add additional information below.
3. No relocation / additional information for uber-stale issues.

*Additional information: not supported by third party tools right now.*
