### ISSUE TITLE
Support for Prometheus' blackbox_exporter

### ISSUE THREAD

**Issue by rfc1036** [inex/IXP-Manager#689]
I am using Prometheus' blackbox_exporter to monitor members' reachability (Nagios is so much 1990s!) and to determine their RTT for community-controlled traffic engineering in the route servers.

Are you interested in integrating something like this?
I will also publish the route servers side of the code once once the API design will be decided.

I am lazy so I have been repurposing the Nagios controller, but it would be better to use different API routing to get both IPv4 and IPv6 addresses with a single request.

The two attached files can be installed as:
* resources/skins/.../api/v4/nagios/customers/rtt-prometheus.foil.php
* resources/skins/.../api/v4/nagios/customers/rtt-list.foil.php

The first API generates the configuration for Prometheus, while the second one is used by the code which computes the RTTs.

[rtt-prometheus.foil.php.txt](https://github.com/inex/IXP-Manager/files/5860178/rtt-prometheus.foil.php.txt)
[rtt-list.foil.php.txt](https://github.com/inex/IXP-Manager/files/5860179/rtt-list.foil.php.txt)

**Comment by barryo** [comment]
I'm not uninterested @rfc1036 !

But I think in the longer term we'll need to find a better way to work with "plugins" so that we don't stick everything into the core. As it stands right now, there are tons of ways of getting data out of IXP Manager including two which I think will get you the information you need: switch provisioning APIs and IX-F Member Export.

I'm going to close this for now but it is something I'll think on for a more agnostic way to handle these. Thanks!
