### ISSUE TITLE
Filtered prefixes tab route server button fails when route limit is higher than the maximum set in birdseye

### ISSUE THREAD

**Issue by moviedo-sc** [inex/IXP-Manager#707]
When an user clicks on the route server name, under the filtered prefixes tab, and the received routes exceed the limit set in birdeye config (1000 routes as default) it fails with the error: 500 | Server Error :: Content not defined.

This confuses the members. It would be better to add a more informative message, or redirect to the Route Search tab.

Thanks,
Mauricio

**Comment by barryo** [comment]
@yannrobin  - a sample of the issue here [can be seen on this link](https://www.inex.ie/ixp/lg/rs1-lan1-ipv4/routes/protocol/pb_0187_as6939).

The issue is Birdseye is limiting the amount of routes that it will return (anti-DoS, anti-service interruption mechanism). 

Can you catch 500's on the looking glass and redirect to the summary page ([like this one](https://www.inex.ie/ixp/lg/rs1-lan1-ipv4)] with a info bar: "The available resource is not available. Most likely the amount of routes exceed the APIs configured maximum threshold."

[releave-v5 and v6 please]
