### ISSUE TITLE
Remove 1239 from static list

### ISSUE THREAD

**Issue by job** [inex/IXP-Manager#716]
AS 1239 appears to have updated their strategy and appears to connect to more and more Route Servers at IXPs

source: https://www.peeringdb.com/asn/1239

https://github.com/inex/IXP-Manager/blob/7cd28f8a331ddee38c1e568056121b481890ddc2/data/travis-ci/known-good/ci-apiv4-b2-rc1-lan1-ipv4.conf#L182

**Comment by nickhilliard** [comment]
do they connect to route servers at all the locations listed on peeringdb?  The port speeds at most of the locations indicate that these are special purpose ixp connections rather than general-purpose #yolo peering.  If they're using RS's at only one or two exchanges, it would be better to leave them in the list and individual ixp operators can modify as necessary.

**Comment by barryo** [comment]
I've brought this into sync with @job's list on https://bgpfilterguide.nlnog.net/guides/no_transit_leaks/

and added some knobs to help avoid skinning - docs @ https://docs.ixpmanager.org/features/routers/#filtering-known-transit-networks

**Comment by ichilton** [comment]
@barryo Just saw this through the mention in the 6.2.0 release notes.

IXP_NO_TRANSIT_ASNS_EXCLUDE looks to be just what we need!

We were skinning that whole file just to remove 6461, so it looks like we can now remove that, revert to stock and just use IXP_NO_TRANSIT_ASNS_EXCLUDE.

Thank you!

Ian
