### ISSUE TITLE
Reseller Uplink Ports are not included in the /api/v4/provisioner/layer2interfaces API response

### ISSUE THREAD

**Issue by ichilton** [inex/IXP-Manager#781]
Members with a reseller uplink port are not included in the /api/v4/provisioner/layer2interfaces API response, but these ports need provisioning, so should be included.

**Comment by nickhilliard** [comment]
The uplink port isn't included yet, and won't be until IXP Manager supports uplink ports properly.  Regular subinterface ports are included.

For the moment, I'd suggest maintaining the uplink port in a separate per-switch config blob.

**Comment by ichilton** [comment]
Hi @nickhilliard,

What do you mean "supports uplink ports properly"?

The interfaces are currently in IXP Manager, so should be available via the API.... or put another way, all interfaces in IXP Manager should be in the API response. If a user does not require configuration for a certain type, they can be ignored by the automation logic.

We want IXP Manager to be the source of truth for all peering configuration (as I think it should be?), but currently we are having to maintain separate static data files for this data, which is undesirable - especially as that data is already in IXPM, just not accessible.

Please would you re-consider the closing/dismissal of this issue?


> For the moment, I'd suggest maintaining the uplink port in a separate per-switch config blob.

This isn't currently available either - requested in: https://github.com/inex/IXP-Manager/issues/772 - but in this case, the configuration should really come from the member ports data and not from a misc config blob.

Thanks,

Ian

**Comment by nickhilliard** [comment]
just for clarification, are you talking about the reseller trunk port, or the subinterface ports?

**Comment by ichilton** [comment]
In a global sense, i'm asking or all ports that are added to IXP Manager should be available via the API.

In this issue (*), i'm wanting to address what IXP Manager labels "Reseller Uplink Ports" - the reseller trunk port - i.e the reseller's physically connected interface.

Background - we have a few resellers who do not peer with us, they just resell. Historically, they were configured as a standard peer + the additional VLANs, but they've never done any peering or brought up any sessions (even to our collector).

To rationalise these, we recently removed their peering ports in IXP Manager and their connected port now just appears in "Reseller Uplink Ports" (see attached images), which now reflects reality.

The problem is, now our automation wants to remove the configuration from their connected ports, because they are no longer in the API response from IXP Manager, even though they are configured, which IMO is incorrect and the only way round this currently is to have external metadata, when that data is already in IXPM, where it should be.

![Screenshot 2022-02-14 at 10 36 46](https://user-images.githubusercontent.com/524196/153848332-29e2dde4-ac86-47cf-8c30-135615b53bf7.png)
![Screenshot 2022-02-14 at 10 36 57](https://user-images.githubusercontent.com/524196/153848335-cf34b802-0d9b-47b3-acf7-65eb40c6d7ca.png)


* I already raised another issue previously (https://github.com/inex/IXP-Manager/issues/770) regarding the "fanout ports", as they are not included in the API response either, despite being configured in IXP Manager. As we are using physical loopbacks for resellers, the fanout port is the reseller side of the loopback, with the VLAN used by the resold connection
(as opposed to the member side of the loopback, which is on the peering VLAN).

**Comment by nickhilliard** [comment]
> We want IXP Manager to be the source of truth for all peering configuration

> In a global sense, i'm asking or all ports that are added to IXP Manager should be available via the API.

totally understand - we'd love to have this too. The underlying issue here is that you run into diminishing returns at a precipitous rate. In terms of reseller ports, this is a problem that we acknowledge needs to be solved properly, in such a way that the data model used in IXP Manager is updated to implement a reasonable enough abstraction of reseller ports that it's useful in the general case.  From the point of view of API stability, if we add reseller physical ports now, without having an adequate data model to represent what's going there properly, then we will need to change the API in future and that can easily end up being a support headache.  We would far prefer to do it right the first time around.

As a general comment, each type of service delivered on a device requires its own data abstraction model and then a presentation model.  E.g. shared vlans wouldn't be the same as p2p pseudowires across the ixp fabric, etc. Any provisioning system acting as an NSOT therefore needs either to fully abstract all service models in a generic enough way that they're usable for all service model consumers (easy enough for basic IXP service, not so easy for more advanced stuff), or else provide the option for per-device config blobs to handle the outlying cases.  Then as the outlying config becomes more widely used, and therefore more generic, it can be pulled back into the data models that IXP Manager handles, and then that chunk of config can be removed from the per-device config blob.

I think we need to probably add a config blob field for each switch and present that in the provisioning layer.  This will cope with what LONAP needs (and other IXPs too), in a completely generic way, without causing future problems in terms of how we would or wouldn't implement reseller port functionality.

**Comment by listerr** [comment]
IIRC, the "Reseller Uplink" ports is/was the **INEX** way of doing resellers and a few changes had to be made to accommodate the **LONAP** setup where resellers also peer themselves on the same port.

Now we change some of them to the originally designed-for model, we can't see it in the JSON output.

This was back in around 2013 though, so things may have changed, or this is forgotten about.

Did INEX move from using reseller "loop / fanout" ports to a different method e.g, Arista new feature for VLAN replication?
How does this work WRT port graphs, stats etc for the resold members?

We have on our roadmap to switch from loops/fanout ports to "Arista just do this in software", but haven't looked again because IXP Manager doesn't (yet) support it?

Anyway, I just made the "mysql query to end all mysql queries " + a method to query what connection data you want, and get the result in JSON. This supports our (probably not all that unique?) use case of "one peering vlan, other private vlans."

I suppose it could also output YAML if that's more useful.

This is also useful as a generic "connections query and reporting tool".

I put it here: https://github.com/listerr/ixpm-connections-json

Not so much that you can marvel at my amazing code(!), but the README describes how it works (adapted from our internal documentation for it, along with some examples.)
