### ISSUE TITLE
PeeringDB "Restrictive" Policy

### ISSUE THREAD

**Issue by rlaager** [inex/IXP-Manager#858]
PeeringDB supports the value "Restrictive" for the policy_general field:
https://www.peeringdb.com/apidocs/#tag/api/operation/list%20net

This is not handled in IXP Manager:
https://github.com/inex/IXP-Manager/blob/67d156f78c07a714270cdf7dcd264988fe419462/resources/views/customer/js/edit.foil.php#L127

I propose that it be treated as "Selective". If that is agreed, I will submit a PR.

**Comment by barryo** [comment]
PeeringDB have selective too though. I don't know what the semantic difference is between restrictive and selective?

We've chosen to not handle it for this reason - IXP Manager operator will need to make the call. 

At INEX, our member application forms have open, selective, closed.

**Comment by rlaager** [comment]
The answer from PeeringDB:
> there is no overall accepted definition. In short
> 
>     selective: you have to meet certain criteria
>     restrictive: forget about getting a peering
> 
> DrPeering explains both terms in detail here [0]
>
> [0] https://drpeering.net/FAQ/What-is-a-selective-peering-policy.php

which also links to here:
https://drpeering.net/FAQ/What-is-a-restrictive-peering-policy.php

So it seems it's shades of grey:

- Open is "yes" or "yes, unless..."
- Selective is "yes, if..."
- Restrictive is "no, unless..."
- No is "no"

Looking at the networks on MICE that have Restrictive set, I'd say one of them is just wrong. (They peer with the route servers!) The other is, I think, meaningfully different than the others that are "Selective". The others that are "Selective" are either likely wrong (they peer with the route servers!) or tend to be content providers who will peer with most any eyeball network of non-trivial size. But the one "legitimate" restrictive is much more limited in who they peer with.

So I think it would be reasonable to align with PeeringDB and add a "Restrictive" option.

**Comment by barryo** [comment]
Thanks for getting the detail from PeeringDB @rlaager 

> restrictive: forget about getting a peering

So that's basically describing it as "closed / no".

You definition of Selective is "yes, if..." / Restrictive is "no, unless..." is basically describing them as synonyms.

My view would be the same: selective ~= restrictive and I'd be happy for the switch to match them on that basis. I would not like to see restrictive added as an option because it doesn't add value, just confusion.

**Comment by lucix-mich** [comment]
Hello Richard,

[...]
> Looking at the networks on MICE that have Restrictive set, I'd say one of them is just wrong. (They peer with the route servers!) The other is, I think, meaningfully different than the others that are "Selective". The others that are "Selective" are either likely wrong (they peer with the route servers!) or tend to be content providers who will peer with most any eyeball network of non-trivial size. But the one "legitimate" restrictive is much more limited in who they peer with.

Don't confuse "peering with the route server" as equivalent to "open peering policy". It has nothing to do. Peering with a route server does not mean that a certain member would automatically send their prefixes to all other RS-connected members. We have a number of members who use route servers to get to the CDN caches, but don't go to anybody else. Community-based filtering is the key here.

Just to add this for clarification.

**Comment by lucix-mich** [comment]
I am wondering if the discussion on this issue here shows one of the fundamental "problem" with IXP Manager.

Of course the origin of IXP Manager is at INEX, and the community is very grateful for the work done by INEX and for making the result available to the community.

On the other hand how often are you forcing your own way of doing things on the other users? In this specific case, for example, I would expect I can tailor the peering policies I make available at my exchange, rather than having to copy exactly those used by INEX, including their term and their meaning.

If there is a generally accepted standard for routing policies, preferably from some RFC or BCP document, then it's fair to restrict to that list. If that is not the case, I would definitely like to see an option for customisation.

You have no idea what policies to publish? Why not use those of INEX, be my guest. You have other policies at your exchange and don't want to change? Customise the list, be my guest. You want to define 10 different policies? Man, I have no idea what that should be good for, but go ahead and be my guest.

I hope to find this open-minded approach more often, and would be ready from the LU-CIX side to help with contributions.
