### ISSUE TITLE
Master branch docker-compose setup broken; web interface error

### ISSUE THREAD

**Issue by jbemmel** [inex/IXP-Manager#875]
Following the steps at https://docs.ixpmanager.org/dev/docker/#tldr-guide-to-get-docker-running leads to

![image](https://github.com/inex/IXP-Manager/assets/2031627/a193822c-3270-4eca-a896-a33e149ca659)

Could this have something to do with `composer install` not being run?

**Comment by barryo** [comment]
Hi @jbemmel - I haven't used Docker is some years for IXP Manager development and probably not since mainline version 4. Unfortunately, any use of Docker for development would need a complete overhaul of the docker-compose files and associated scripts. 

IMHO, you're better off developing locally (e.g. on MacOS we use Valet + Homebrew) or use the Vagrant system.

Sorry for the bad news :-(
